name: Test Email Action

on:
  push:
    branches:
      - main  # Or 'master' or whichever branch you want

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 24ds2000059@ds.study.iitm.ac.in
        run: echo "Hello, world!"
